services:

  user-service:
    container_name: user-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
    ports:
      - ${USER_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  analysis-service:
    container_name: analysis-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${ANALYSIS_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${ANALYSIS_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  client-service:
    container_name: client-service-DEBUG
    ports:
      - "4200:80"

  form-service:
    container_name: form-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${FORM_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${FORM_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  gateway-service:
    container_name: gateway-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
    ports:
      - ${GATEWAY_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  group-service:
    container_name: group-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${GROUP_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${GROUP_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  media-service:
    container_name: media-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${MEDIA_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${MEDIA_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  technique-service:
    container_name: technique-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${TECHNIQUE_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${TECHNIQUE_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  localisation-service:
    container_name: localisation-service-DEBUG
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:${DEFAULT_PORT_INTERNAL}"
      - "DefaultConnection=Server=${DB_NAME},${SQL_PORT_INT};Initial Catalog=${LOCALISATION_DB_INITIAL_CAT};User Id=${DB_USER};Password=${SA_PASSWORD}"
    ports:
      - ${LOCALISATION_PORT_EXT}:${DEFAULT_PORT_INTERNAL}

  sql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-USA",
          "-P${SA_PASSWORD}",
          "-Q",
          "SELECT 1"
        ]
    volumes:
      - prometheus-sqldata:/var/opt/mssql
      - prometheus-sqluser:/var/opt/sql
    ports:
      - ${SQL_PORT_EXT}:${SQL_PORT_INT}

  rabbitmq:
    user: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=${RABBITMQ_NODENAME}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_EXT_PORT_1}:5672"
      - "${RABBITMQ_EXT_PORT_2}:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs/:/var/log/rabbitmq/

networks:
  local:
    driver: bridge
